#!/bin/bash
set -e
((EUID==0)) || { echo "run as root"; exit 1; }

COPY="/var/lib/tmparch"
SFS="/var/lib/tmparch.sfs"
TMP=$(mktemp -d /tmp/container-XXXX)
trap 'rm -rf "$TMP"' EXIT

[[ -f $SFS ]] || {
  mkdir -p "$COPY"
  pacstrap "$COPY" base base-devel
  passwd --root "$COPY" -d root
  mksquashfs "$COPY" "$SFS" -comp zstd
  rm -rf "$COPY"
}

unsquashfs -f -d "$TMP" "$SFS"
systemd-nspawn -D "$TMP" --boot --network-veth

